### ISSUE TITLE
Will Tether USDT be supported?

### ISSUE THREAD

**Issue by itekhi** [bitcart/bitcart-sdk#48]
Hi! I was wondering if bitcart supports Tether USDT, as I see at https://bitcart.ai/coins - it doesn't 😢.
Will Tether be supported in future? Or there's some particular reason why not?

**Comment by MrNaif2018** [comment]
Now re-read that page (:
![изображение](https://github.com/bitcart/bitcart-sdk/assets/39452697/d737ff89-de8a-4014-a592-c7fd21c61de2)

**Comment by itekhi** [comment]
@MrNaif2018 But the platform is not Tether, am I misunderstanding something?

**Comment by itekhi** [comment]
Update:
That was... stupid ;)
Sorry, I understood that the Tether is a standart of tokens. I wanted to ask about Tron, and Tron is already supported ;)

I didn't understand how it works, I thought you need to pass specific coins when paying with some platform.
I guess bitcart automatically understands what token was used?

**Comment by itekhi** [comment]
@MrNaif2018 Hi!
I still can't understand how do i send `USDT` in `Tron` network... Could you please explain how to do it?
I created 2 wallets in `Tron Nile Network` and added test funds to the first one.
Instantiated `TRX` with `xpub` from the first wallet, now I can send funds from one wallet to another, but it is always `TRX`...
I tried to pass `10 USDT` to `trx.pay_to()` but it errors with `decimal.ConversionSyntax` ;(
